# Generated by Django 4.0.1 on 2022-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='Users.tags'),
        ),
    ]
